#!/bin/sh
# File generated by ocamlbuild

cd /home/nogw/Desktop/learning-ocaml/front_end_for_simPL

rm -f lexer.ml
rm -f parser.ml
# Also clean the script itself
rm -f /home/nogw/Desktop/learning-ocaml/front_end_for_simPL/_build/sanitize.sh
